### ISSUE TITLE
How many miles do you bike a week? Is there a routine you follow? 

### ISSUE THREAD

**Issue by amjith** [fool/ama#1]

**Comment by nolessafool** [comment]
The number of miles a week I bike varies greatly - it's definitely been north of 500 while I'm on tour, and it's been 0 while I'm on vacation somewhere without a bike.  On average, I bike 30 miles a week to/from work, and then not having a car means I additionally bike "anywhere else" I need to go within reason.  It probably averages out to 50 miles a week on average - more when it's sunny and less when it's rainy.  I've had (one) >8,000 mile year and (one) <1,000 mile year since I stopped driving full-time in 2006.

I bike everywhere in town that I can manage, and that can include grocery shopping, or even helping a friend move by bike (see http://shift2bikes.org/allbike.php#Move_X_Bike for more details on how that works)

I'm not opposed to other modes of transit: 
- I fly to San Francisco to work (I keep a bike in my office there so I can still get some exercise and get around cheaply and sleep well at night, which in general works better if I get some exercise),
-  I drive out to the country with my partner when she wants to hike, 
- and I love portland's transit for both a fall-back ("don't feel like fixing this flat out on the side of the road in the rain") and to extend my range without wearing me out - if I'm going west of Hillsboro, I usually start with the MAX.
