### ISSUE TITLE
Legend says that you're "extraordinarily outgoing and easy-to-not-piss off". How do you manage that?

### ISSUE THREAD

**Issue by amjith** [fool/ama#2]
Especially when the person you're dealing with is being unpleasant. If possible, can you cover both in person interactions as well as customer support/online interactions?

**Comment by nolessafool** [comment]
I have a few techniques I use.  This isn't life advice so much as "how I manage it" so YMMV if you try to duplicate this:

- **appreciate the variety in the universe**:  I like variety.  I like it a lot.  Boredom is the thing that gets me down, and what isn't boring?  Being surprised by a new point of view or behavior, and attempting to understand (if not appreciate, or agree with) it.
- **pick your battles**:  I care a lot!  But I don't care a lot about everything.  I often deem it more useful to consider that others care more about something than I do, and as long as it isn't "my life vs yours", I can let them win that battle so we can continue to interact without bad feelings.  Do I agree with them?  Not always, but I don't disagree loudly, either.
- **appreciate what life brings**:  I often don't make plans, preferring to drift on the water as things come up.  So I try to find a way to "appreciate" the weird mental spaces that considering those novel viewpoints brings, and trains of thought they can spark.  Often both participants in a non-heated conversation about a heated topic refine their viewpoints, and understanding is increased - even again if not agreement.  Sometimes respect is more important than agreement :)
- **don't take things personally**:  This is the hardest one to remember.  If someone's mad, it's not really about what I've done - it's about how they've chosen to perceive and receive it.  Many times, e.g. at work, the thing that is angering is literally not anything I had anything to do with - an outage, a design decision, etc - and while they are legitimately mad that their business is suffering - and they are acting mad at me - I don't have to own it (but I might to calm them down), and I don't have to choose to be offended just because they are unpleasant or insulting.

Those are general and work in both cases of online and in person in my mind, but in person, I more often agree to disagree vocally - online one can just "ignore the comment" instead of engaging, in person when someone's in your face it's a bit harder.  I often find that one can de-escalate simply by engaging - "tell me more, let's talk through that together" rather than opposing.  Clearly this doesn't work at e.g. political rallies where there are parties dead set on "warring" opinions.  But - I just don't go to those if I have the chance.  

When it's something more transient like my bike ride blocking an irate driver, I try smiling and addressing their concern - which is usually closer to "we'll be out of your way in a minute so you can go" than "we're terrible scofflaws that deserve to burn in hell".  Despite perhaps expressing the latter opinion - it is in fact about them, not about us, and addressing the "root cause" is often a painless road to a solution.  It's not that we "solved" the 1 minute delay we caused, but that we solved the "slowing you down" problem by getting out of the way, and acknowledged and apologized for the inconvenience - that can go a long way :)
